version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: ./dockerfiles/development/django/Dockerfile
    container_name: backend
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./core:/app
    env_file:
      - envs/development/django/.env
  
  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - '5000:80'
      - '25:25'
      - '143:143'
    volumes:
        - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__HostName=smtp4dev

  master:
    image: locustio/locust
    ports:
     - "8089:8089"
    restart: on-failure
    volumes:
      - ./core/locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://backend:8000
  
  worker:
    image: locustio/locust
    restart: on-failure
    volumes:
      - ./core/locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master
volumes:
  smtp4dev-data: