version: "3.9"

services:

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d/production/default.conf:/etc/nginx/conf.d/deault.conf:ro
      - static_volume:/home/app/static
      - media_volume:/home/app/media
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - redis
      - backend
    networks:
      - backend-network

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
    - ./certbot/www/:/var/www/certbot/:rw
    - ./certbot/conf/:/etc/letsencrypt/:rw
    depends_on:
      - nginx
    networks:
      backend-network:


  redis:
    image: redis:6.2.7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - ./redisdata:/data
    networks:
      - backend-network
    
  backend:
    build:
      context: .
      dockerfile: ./dockerfiles/production/django/Dockerfile
    container_name: backend
    restart: always
    command:  gunicorn core.wsgi --bind 0.0.0.0:8000
    expose:
      - "8000"
    volumes:
      - ./core:/app
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - envs/production/django/.env
    depends_on:
      - redis
      - db
    networks:
      - backend-network

  worker-celery:
    build:
      context: .
      dockerfile: ./dockerfiles/production/django/Dockerfile
    command: celery -A core worker --loglevel=info
    container_name: celery-worker
    restart: always
    depends_on:
      - redis
      - backend
    volumes:
     - ./core:/app
    networks:
      - backend-network

  db:
    image: postgres:13-alpine
    container_name: postgres
    ports:
    - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - envs/production/postgres/.env
    networks:
      - backend-network

volumes:
  static_volume:
  media_volume:
  postgres_data:

networks:
  backend-network: