version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: ./dockerfiles/development/django/Dockerfile
    container_name: backend
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./core:/app
    env_file:
      - envs/development/django/.env