# Generated by Django 3.2.15 on 2022-09-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_auto_20220920_2213"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verify",
            field=models.BooleanField(default=False),
        ),
    ]
