# Generated by Django 3.2.15 on 2022-09-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_comment_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.ManyToManyField(
                blank=True, null=True, to="blog.Category"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                default="blog/post_pics/default.jpg",
                null=True,
                upload_to="blog/post_pics/",
            ),
        ),
    ]
