# Generated by Django 3.2.15 on 2022-09-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_post_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.ManyToManyField(blank=True, to="blog.Category"),
        ),
    ]
