# Generated by Django 3.2.15 on 2022-09-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog/post_pics/default.jpg', upload_to='blog/post_pics/'),
        ),
    ]
